name: Characters Engine Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Run Characters Engine Unit Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: characters_engine

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.10.1"

      - name: Get dependencies
        run: flutter pub get

      - name: Run unit tests
        run: flutter test
